#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Hubs,  S3, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, driveLeft)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, driveRight)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     LeftMotor,     tmotorTetrix, openLoop, reversed, driveLeft)
#pragma config(Motor,  mtr_S1_C1_2,     RightMotor,    tmotorTetrix, PIDControl, driveRight)
#pragma config(Motor,  mtr_S3_C1_1,     collect,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     raise,         tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Yellow is on the right for the servo controller
void initializeRobot()
{
	return;
}
#include "JoystickDriver.c"
//Int all drive systems including deadzone and drive.
int lDrive = 0;
int rDrive = 0;
int deadzone = 2;
int collection = 0;
task main()
{
	initializeRobot();

	servo[servo1] = 0;  //Changes the position of servo1 to 0
	servoTarget[servo1] = 0;  //Changes the position of servo1 to 0
	servo[servo2] = 0;  //Changes the position of servo2 to 0
	servoTarget[servo2] = 0;  //Changes the position of servo2 to 0
	//All Joystick Controls that are for driving//
	while(true)
	{
		getJoystickSettings(joystick);

		if(abs(joystick.joy1_y2)>deadzone)
		{
			rDrive = joystick.joy1_y2 / 1.5;
		}
		if((abs(joystick.joy1_y1)>deadzone))
		{
			lDrive = joystick.joy1_y1 / 1.5;

		}
		if (abs(joystick.joy1_y1)<deadzone)
		{
			lDrive = 0;
		}
		if (abs(joystick.joy1_y2)<deadzone)
		{

			rDrive = 0;
		}
		/* ---- Servo --- */
		if(joy1Btn(6) == 1)
		{
			servo[servo1] = 160;  //Changes the position of servo1 to 160
			servoTarget[servo1] = 160;  //Changes the position of servo1 to 160
			servo[servo2] = 160;  //Changes the position of servo2 to 160
			servoTarget[servo2] = 160;  //Changes the position of servo2 to 160
		}
		if(joy1Btn(5) == 1)
		{
			servo[servo1] = 0;  //Changes the position of servo1 to 0
			servoTarget[servo1] = 0;  //Changes the position of servo1 to 0
			servo[servo2] = 0;  //Changes the position of servo2 to 0
			servoTarget[servo2] = 0;  //Changes the position of servo2 to 0
		}
		/* -- Collector -- */
		if(joy2Btn(5) == 1)
		{
			collection = 80;
		}

		if(joy2Btn(6) == 1)
		{
			collection = -80;
		}
		/* -- Lift Mechanism -- */
		if(joy2Btn(1) == 1) //first spot
		{
	   		nMotorEncoder[raise] = 0; //Clears motor(raise) encoder.
	   		nMotorEncoderTarget[raise] = 1800; //Sets motor to move until encoder is equal to 1800 degrees (first spot)
	   	  motor[raise] = 75;
}
}
while(true)
		//Halfspeed button
		if(joy1Btn(1) == 1)
		{
			rDrive = rDrive / 2;
			lDrive = lDrive / 2;
		}
		nMotorEncoder[raise] = 0; //Resets encoder to 0
		//
	  //Power encoders at 50 until the encoders reach one revolution
		//
		while (nMotorEncoder[raise] < 1440)
  {
	motor[raise] = 50;
	}
	//
	// Stop the motors after done raising
	//
	motor[raise] = 0;
	}
